from pathlib import Path

TOP_K = 10
CANDIDATE_POOL_SIZE = 80
GLOBAL_CANDIDATE_POOL_SIZE = 500
GLOBAL_CANDIDATE_STORE_SIZE = 300
COLD_START_SLICE_SIZE = 200
FLUSH_INTERVAL_SEC = 1
RECOMPUTE_INTERVAL_SEC = 1
GLOBAL_REBUILD_EVERY_N_CYCLES = 30
FLUSH_BATCH_SIZE = 50
EXPLORATION_RATE = 0.0
MMR_LAMBDA = 1.0
POPULARITY_BOOST = 0.15
LIKE_WEIGHT = 3.0
DISLIKE_WEIGHT = 4.0

DATA_DIR = Path(__file__).resolve().parent / 'data'
INTERACTIONS_PATH = DATA_DIR / 'interactions.csv'

CATALOG_ALL_KEY = 'catalog:all'
CATALOG_ITEM_PREFIX = 'catalog:item:'
GENRE_INDEX_PREFIX = 'genre:'
TOP_GENRES_PER_USER = 3
MIN_GENRE_POOL_SIZE = 200
MAX_SCORING_POOL_SIZE = 400
GENRE_POOL_BACKFILL_SIZE = 200
SCORING_MMR_INPUT_SIZE = 80
CATALOG_CACHE_TTL_SEC = 60
USER_CANDIDATES_PREFIX = 'user_candidates:'
USER_DISLIKED_PREFIX = 'user_disliked:'
GLOBAL_CANDIDATES_KEY = 'global_candidates'
IMPRESSIONS_HASH_KEY = 'impressions'
RABBITMQ_QUEUE_NAME = 'user_interactions'
